version: '3'
services:
  frontend:
    build:
      context: ./Front End API
      dockerfile: Dockerfile.front
    ports:
      - "3030:3030"    

  backend: 
    build:
      context: ./REST API
      dockerfile: Dockerfile.back
    ports: 
      - "3000:3000"
    depends_on:
      - db

  db:
    volumes:
      - hcm_db:/data/db
    image: mongo:latest
    ports:
      - "27018:27017"

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus/config.yml:/etc/prometheus/config.yml
    command:
      - '--config.file=/etc/prometheus/config.yml'
    ports:
      - '9090:9090'

  grafana:
    image: grafana/grafana-enterprise
    ports:
      - '5000:3000'
    volumes:
      - grafana-storage:/var/lib/grafana

volumes:
   hcm_db:
   prometheus-data:
   grafana-storage: {}
